#pragma once

#include <cstdint>
#include <functional>
#include <string>
#include <string_view>
#include <vector>

namespace cad::naming {

/// How an element came to exist.
///
/// The first four map onto BRepBuilderAPI_MakeShape's reports. `Boundary` does not — it is
/// the load-bearing idea of this scheme and is explained below.
enum class Provenance : std::uint8_t {
    Primitive,   ///< a face created by a primitive constructor, tagged by the constructor
                 ///<   itself (BRepPrimAPI_MakeBox::TopFace() etc.), never by index
    Generated,   ///< a NEW element the op created from a source element
                 ///<   (the fillet face generated by edge E)
    Modified,    ///< the SAME element, altered (a face trimmed by a boolean)
    Boundary,    ///< derived from the set of higher-dimensional elements this element bounds
    Merged,      ///< several source elements became one; siblings become aliases
};

const char* toString(Provenance) noexcept;

/// One step in an element's derivation history.
struct NameStep {
    std::uint32_t featureSerial = 0;   ///< which document feature performed this op
    std::uint16_t opTag = 0;           ///< which sub-operation within that feature
    Provenance provenance = Provenance::Primitive;
    std::uint32_t discriminator = 0;   ///< distinguishes siblings; see ElementName docs
    std::vector<std::uint64_t> parents;  ///< digests of the parent names (sorted, canonical)

    friend bool operator==(const NameStep&, const NameStep&) = default;
};

/// A topological element's stable identity: the chain of operations that produced it.
/// NOT an index into anything.
///
/// ## The scheme
///
/// Faces are named by provenance. Everything of lower dimension — edges, vertices — is named
/// by the SET OF FACES IT BOUNDS (`Provenance::Boundary`, with the bounding faces' digests
/// in `parents`, sorted so the name is canonical).
///
/// This is why the acceptance test can pass. Change a box's width and OCCT renumbers every
/// sub-shape, but the top face is still the top face and the front face is still the front
/// face, so the edge {Top, Front} is still the same edge. Face identity is the only thing
/// that has to be tracked through operations, and faces are exactly what OCCT's
/// Generated/Modified reports cover best.
///
/// ## The hard cases
///
///  - **Split**: an edge divides in two. Both children bound the same face pair, so both
///    derive the same Boundary name and are separated only by `discriminator`. We order
///    siblings by their midpoint in a canonical frame — the one genuinely fragile part of
///    this scheme, and the main source of NamingLost. A reference to the parent resolves to
///    ALL children (ElementMap::resolveAll), because "fillet this edge" means the whole
///    edge, not an arbitrary half of it.
///
///  - **Merge**: two faces become one. The lexicographically smallest child name is
///    canonical; the others become aliases, so references to either survive.
///
///  - **Delete**: the element is gone. The reference resolves to nothing and the dependent
///    feature fails legibly. It must NEVER rebind to a neighbour — a wrong answer here
///    silently corrupts a user's model, which is worse than an error.
class ElementName {
public:
    ElementName() = default;
    explicit ElementName(std::vector<NameStep> steps);

    [[nodiscard]] bool isNull() const noexcept { return steps_.empty(); }
    [[nodiscard]] const std::vector<NameStep>& steps() const noexcept { return steps_; }

    /// Append a derivation step, producing the child's name.
    [[nodiscard]] ElementName derive(NameStep step) const;

    /// This name with `discriminator` cleared on the final step: the "family" a split's
    /// children belong to. Used by resolveAll.
    [[nodiscard]] ElementName family() const;

    /// Stable 64-bit digest. Collisions are resolved by comparing the full chain; this is
    /// an accelerator, not an identity.
    [[nodiscard]] std::uint64_t digest() const noexcept { return digest_; }

    /// Round-trippable text form for the native file, logs, and the plugin ABI.
    /// e.g. "P0.0#0" or "B7.0#1[a3f2,91c4]"
    [[nodiscard]] std::string toString() const;
    static ElementName parse(std::string_view);

    friend bool operator==(const ElementName& a, const ElementName& b) {
        return a.digest_ == b.digest_ && a.steps_ == b.steps_;
    }
    friend bool operator<(const ElementName& a, const ElementName& b);

private:
    void recomputeDigest() noexcept;

    std::vector<NameStep> steps_;
    std::uint64_t digest_ = 0;
};

/// What the rest of the system passes around, and what crosses the C plugin ABI.
struct ElementId {
    std::uint64_t digest = 0;
    friend bool operator==(const ElementId&, const ElementId&) = default;
};

}  // namespace cad::naming

template <>
struct std::hash<cad::naming::ElementId> {
    std::size_t operator()(const cad::naming::ElementId& id) const noexcept {
        return static_cast<std::size_t>(id.digest);
    }
};

template <>
struct std::hash<cad::naming::ElementName> {
    std::size_t operator()(const cad::naming::ElementName& n) const noexcept {
        return static_cast<std::size_t>(n.digest());
    }
};
