#pragma once

#include "cad/kernel/Result.h"
#include "cad/kernel/Shape.h"

namespace cad::kernel {

/// Rigid translation. Returns an Operation rather than a Shape because
/// BRepBuilderAPI_Transform reports Modified(), which is how names survive the move.
Result<Operation> translate(const Shape&, double dx, double dy, double dz);

/// Rigid rotation about an axis, by the right-hand rule.
///
/// `axis` need not be normalised; it is only a direction, and requiring unit length at the call
/// site would push a square root into every caller for no gain.
///
/// A zero angle is allowed, unlike a zero-distance extrude. The difference is that this one
/// produces a perfectly good shape — the input, unmoved — whereas a zero extrude produces a
/// degenerate solid that reports success and then fails everything downstream. Whether a no-op is
/// worth recording as a feature is a question for the layer that has a user to answer to.
Result<Operation> rotate(const Shape&, const double origin[3], const double axis[3],
                         double angleRadians);

/// Reflection in the PLANE through `origin` with the given `normal`.
///
/// A plane, not a point or a line: mirroring a part about the plane it was designed against is the
/// case every CAD system means by "mirror", and the other two symmetries are rotations in disguise.
///
/// This is the one transform that REVERSES orientation, which is why it is worth having as its own
/// operation rather than a `gp_Trsf` a caller assembles. A reflected solid whose faces still point
/// the way they used to is inside-out: it validates, it draws, and every boolean against it does
/// the opposite of what was asked. The output is checked before it is returned.
Result<Operation> mirror(const Shape&, const double origin[3], const double normal[3]);

/// Sweeps a profile linearly into a solid — the extrude every sketch-based feature is built on.
///
/// Returns an `Operation` rather than a bare `Shape` because the naming layer has to walk it: the
/// side faces of an extrusion are GENERATED by the profile's edges, and the caps are generated by
/// the profile's faces. Without that provenance, a fillet on an extruded edge could not survive the
/// profile being edited — which is the entire point of ADR 0005.
Result<Operation> extrude(const Shape& profile, double dx, double dy, double dz);

/// Sweeps a profile about an axis.
///
/// `angleRadians` of 2*pi is a full revolution — the common case and the one worth getting exactly
/// right, so callers pass the full turn rather than a flag meaning "all the way".
///
/// The profile must not CROSS the axis. OCCT produces a self-intersecting solid when it does, which
/// passes every check we make and fails much later in a boolean; the caller is better placed to
/// explain that to a user than a geometry error three operations downstream.
Result<Operation> revolve(const Shape& profile, const double origin[3], const double axis[3],
                          double angleRadians);

}  // namespace cad::kernel
