#pragma once

#include "cad/kernel/Result.h"
#include "cad/kernel/Shape.h"

namespace cad::kernel {

/// Rigid translation. Returns an Operation rather than a Shape because
/// BRepBuilderAPI_Transform reports Modified(), which is how names survive the move.
Result<Operation> translate(const Shape&, double dx, double dy, double dz);

/// Sweeps a profile linearly into a solid — the extrude every sketch-based feature is built on.
///
/// Returns an `Operation` rather than a bare `Shape` because the naming layer has to walk it: the
/// side faces of an extrusion are GENERATED by the profile's edges, and the caps are generated by
/// the profile's faces. Without that provenance, a fillet on an extruded edge could not survive the
/// profile being edited — which is the entire point of ADR 0005.
Result<Operation> extrude(const Shape& profile, double dx, double dy, double dz);

}  // namespace cad::kernel
