// M1 ACCEPTANCE TEST — the gate for the whole project.
//
// The scenario that defines parametric B-rep CAD:
//
//   1. build a box
//   2. the user picks ONE edge and fillets it
//   3. an upstream parameter changes; the shape is rebuilt from scratch and every OCCT
//      index is different
//   4. the fillet must still be on the edge the user picked
//
// Naive index-based references pass step 3 by accident for small changes and break silently
// for large ones. That silent breakage is the topological naming problem.

#include "Model.h"

#include "cad/kernel/Booleans.h"
#include "cad/kernel/Transform.h"

#include <catch2/catch_test_macros.hpp>

#include <set>
#include <catch2/generators/catch_generators.hpp>
#include <catch2/generators/catch_generators_range.hpp>

#include <cstdlib>
#include <string>

using namespace cadtest;
using cad::kernel::BoxFace;
using cad::naming::contentHash;
using cad::naming::NameStep;
using cad::naming::Provenance;

namespace {

/// The name the fillet face should carry: generated by the picked edge, in feature 2.
ElementName expectedFilletFace(const ElementName& pickedEdge, std::uint32_t serial = 2) {
    NameStep s;
    s.featureSerial = serial;
    s.opTag = 0;
    s.provenance = Provenance::Generated;
    s.parents = {pickedEdge.digest()};
    return pickedEdge.derive(s);
}

}  // namespace

TEST_CASE("M1: a filleted edge survives upstream parameter changes", "[m1][naming]") {
    // Pick the edge once, at the nominal size, the way a user would.
    auto nominal = box(100.0, 60.0, 40.0);
    REQUIRE(nominal.ok());
    auto pickedR = edgeBetween(nominal.value(), BoxFace::ZMax, BoxFace::YMin);
    REQUIRE(pickedR.ok());
    const ElementName picked = pickedR.value();

    // Sweep the width. The fillet must land on the same NAMED edge every time, even though
    // OCCT's sub-shape indices are free to change arbitrarily between rebuilds.
    const double width = GENERATE(range(20.0, 220.0, 4.0));  // 50 values
    INFO("width = " << width);

    auto rebuiltBox = box(width, 60.0, 40.0);
    REQUIRE(rebuiltBox.ok());

    // The reference taken at 100mm still resolves at every other width.
    REQUIRE_FALSE(rebuiltBox.value().map.resolveAll(picked).empty());

    auto filleted = fillet(rebuiltBox.value(), picked, 5.0);
    REQUIRE(filleted.ok());
    CHECK(filleted.value().shape.validate().ok());

    // The fillet face is present and derives from the edge the user picked — not from
    // whichever edge happened to land at the same index.
    CHECK(filleted.value().map.resolve(expectedFilletFace(picked)).has_value());

    // Nothing in the result may be anonymous. An unnamed element is a future silent
    // rebinding bug; propagate() already fails on this, so reaching here means it held.
    CHECK(filleted.value().map.unnamed(filleted.value().shape).empty());
}

// ---------------------------------------------------------------------------------------
// The adversarial cases. These decide whether the scheme actually works; the sweep above is
// the easy half. Each must FAIL LOUDLY rather than rebind to the wrong element — a wrong
// answer here silently corrupts a user's model, the worst failure mode a CAD system has.

TEST_CASE("M1: a split edge keeps both children", "[m1][naming]") {
    auto base = box(100.0, 60.0, 40.0);
    REQUIRE(base.ok());
    auto pickedR = edgeBetween(base.value(), BoxFace::ZMax, BoxFace::YMin);
    REQUIRE(pickedR.ok());
    const ElementName picked = pickedR.value();

    // A notch through the middle of that edge divides it in two. Both children bound the
    // same face pair, so they share a family and differ only in discriminator.
    auto toolBox = box(20.0, 20.0, 20.0, /*serial*/ 10);
    REQUIRE(toolBox.ok());
    auto tool = translated(toolBox.value(), 40.0, -5.0, 30.0);
    REQUIRE(tool.ok());

    auto notched = cut(base.value(), tool.value());
    REQUIRE(notched.ok());

    // The exact reference no longer resolves — the original edge is gone as a single entity.
    // The family does, and it has two members.
    const auto children = notched.value().map.resolveAll(picked);
    INFO("resolved " << children.size() << " children for " << picked.toString());
    REQUIRE(children.size() == 2);

    // "Fillet this edge" therefore applies to both.
    auto filleted = fillet(notched.value(), picked, 3.0);
    REQUIRE(filleted.ok());
    CHECK(filleted.value().shape.validate().ok());
}

TEST_CASE("M1: a vanished edge fails loudly and never rebinds", "[m1][naming]") {
    auto base = box(100.0, 60.0, 40.0);
    REQUIRE(base.ok());
    auto pickedR = edgeBetween(base.value(), BoxFace::ZMax, BoxFace::YMin);
    REQUIRE(pickedR.ok());
    const ElementName picked = pickedR.value();

    // Chop the entire top-front corner away across the full width. Top and Front both
    // survive but no longer touch, so no edge bounds that pair any more.
    auto toolBox = box(140.0, 30.0, 30.0, /*serial*/ 10);
    REQUIRE(toolBox.ok());
    auto tool = translated(toolBox.value(), -20.0, -10.0, 30.0);
    REQUIRE(tool.ok());

    auto chopped = cut(base.value(), tool.value());
    REQUIRE(chopped.ok());

    // Nothing resolves — and crucially, nothing *else* resolves either.
    CHECK(chopped.value().map.resolveAll(picked).empty());

    // The dependent feature reports a legible, specific failure.
    auto filleted = fillet(chopped.value(), picked, 3.0);
    REQUIRE_FALSE(filleted.ok());
    CHECK(filleted.error().code == ErrorCode::NamingLost);
    INFO(filleted.error().message);
    CHECK(filleted.error().message.find("no longer exists") != std::string::npos);
}

TEST_CASE("M1: merged faces keep both references alive", "[m1][naming]") {
    auto a = box(100.0, 60.0, 40.0);
    REQUIRE(a.ok());
    auto bBase = box(100.0, 60.0, 40.0, /*serial*/ 20);
    REQUIRE(bBase.ok());
    auto b = translated(bBase.value(), 100.0, 0.0, 0.0);
    REQUIRE(b.ok());

    const auto aTop = faceName(a.value(), BoxFace::ZMax);
    REQUIRE(aTop.ok());

    auto merged = fuseAndUnify(a.value(), b.value());
    REQUIRE(merged.ok());
    CHECK(merged.value().shape.validate().ok());

    // The two coplanar top faces are now one face. A reference to the original top face of
    // box A must still resolve — to the merged face.
    const auto resolved = merged.value().map.resolve(aTop.value());
    REQUIRE(resolved.has_value());
    CHECK_FALSE(resolved->isNull());
    CHECK(resolved->type() == cad::kernel::ShapeType::Face);
}

TEST_CASE("M1: naming is deterministic within a process", "[m1][naming]") {
    // Non-determinism almost always enters through pointer-ordered iteration of OCCT maps.
    // Two independent builds of the same model must agree exactly.
    auto first = box(100.0, 60.0, 40.0);
    auto second = box(100.0, 60.0, 40.0);
    REQUIRE(first.ok());
    REQUIRE(second.ok());

    CHECK(nameStrings(first.value()) == nameStrings(second.value()));
    CHECK(contentHash(first.value().shape, first.value().map).hex() ==
          contentHash(second.value().shape, second.value().map).hex());

    auto e1 = edgeBetween(first.value(), BoxFace::ZMax, BoxFace::YMin);
    auto e2 = edgeBetween(second.value(), BoxFace::ZMax, BoxFace::YMin);
    REQUIRE(e1.ok());
    REQUIRE(e2.ok());
    auto f1 = fillet(first.value(), e1.value(), 5.0);
    auto f2 = fillet(second.value(), e2.value(), 5.0);
    REQUIRE(f1.ok());
    REQUIRE(f2.ok());

    CHECK(nameStrings(f1.value()) == nameStrings(f2.value()));
    CHECK(contentHash(f1.value().shape, f1.value().map).hex() ==
          contentHash(f2.value().shape, f2.value().map).hex());
}

// The cross-process half of determinism lives in m1_determinism_subprocess.cpp, because it
// needs control of main(). Without it the DDC's shared tier produces cross-machine misses
// and is worthless.

TEST_CASE("M1: names round-trip through text", "[m1][naming]") {
    auto m = box(100.0, 60.0, 40.0);
    REQUIRE(m.ok());
    for (const auto& name : m.value().map.allNames()) {
        const auto text = name.toString();
        INFO(text);
        CHECK(ElementName::parse(text) == name);
    }
}

// ── copies, and why Pattern cannot be built by propagate-and-fuse ───────────────────────
//
// A pattern makes N copies of ONE source, so every copy's faces trace back to the same
// provenance. These two cases pin what that costs and the guard that now catches it. Written as an
// experiment before Pattern was designed, and kept because both halves are load-bearing: the
// limitation shapes how Pattern must be built, and the guard is what stops it being built wrongly.

TEST_CASE("M1: a copy is indistinguishable from its source by name", "[m1][naming][multiplicity]") {
    // The root of it. A rigid transform reports its elements as Modified — "the SAME element,
    // moved" — which is exactly right for a MOVE and exactly wrong for a COPY. The naming layer
    // cannot tell the two apart, so a translated body carries the original's names verbatim.
    auto source = box(40.0, 30.0, 20.0, /*serial=*/1);
    REQUIRE(source.ok());
    const auto top = faceName(source.value(), BoxFace::ZMax);
    REQUIRE(top.ok());

    // And a fresh feature serial does not separate them: the serial rides on names the operation
    // MINTS, and a transform mints none.
    for (const std::uint32_t serial : {2u, 7u, 99u}) {
        auto moved = cad::kernel::translate(source.value().shape, 200.0, 0.0, 0.0);
        REQUIRE(moved.ok());
        cad::naming::NamingContext ctx(serial, 0);
        const cad::kernel::Shape* shape = &source.value().shape;
        const cad::naming::ElementMap* map = &source.value().map;
        auto copied = ctx.propagate(moved.value(), {shape}, {map});
        REQUIRE(copied.ok());
        INFO("feature serial " << serial);
        CHECK(copied.value().resolve(top.value()).has_value());
    }
}

TEST_CASE("M1: two copies of one source refuse to be named together", "[m1][naming][multiplicity]") {
    // What a linear pattern's final step would do, and what it used to do SILENTLY: 52 bindings
    // with 46 unique names, no unnamed elements, and `resolveAll` returning one arbitrary winner
    // because it short-circuits on an exact hit before consulting the family. A fillet on "the top
    // face" of a six-instance pattern would have rounded one of them, with a green recompute.
    //
    // Refused now, at the moment it happens. That does not make Pattern work — it makes Pattern
    // impossible to build the wrong way, which is the point of ADR 0005. Building it right means
    // MINTING a name per instance rather than propagating one: NameStep::discriminator already
    // exists to separate otherwise-identical siblings, so the name format needs no change.
    auto source = box(40.0, 30.0, 20.0, 1);
    REQUIRE(source.ok());

    auto moved = cad::kernel::translate(source.value().shape, 200.0, 0.0, 0.0);
    REQUIRE(moved.ok());
    cad::naming::NamingContext copyCtx(2, 0);
    const cad::kernel::Shape* sourceShape = &source.value().shape;
    const cad::naming::ElementMap* sourceMap = &source.value().map;
    auto copyMap = copyCtx.propagate(moved.value(), {sourceShape}, {sourceMap});
    REQUIRE(copyMap.ok());
    const cad::kernel::Shape copyShape = moved.value().shape();

    auto fused = cad::kernel::booleanFuse(source.value().shape, copyShape);
    REQUIRE(fused.ok());

    cad::naming::NamingContext fuseCtx(3, 0);
    auto fusedMap = fuseCtx.propagate(fused.value(), {sourceShape, &copyShape},
                                      {sourceMap, &copyMap.value()});
    REQUIRE_FALSE(fusedMap.ok());
    CHECK(fusedMap.error().code == cad::kernel::ErrorCode::NamingLost);
    INFO(fusedMap.error().detail);
    CHECK_FALSE(fusedMap.error().detail.empty());
}

TEST_CASE("M1: a named copy is a different thing from its source", "[m1][naming][multiplicity]") {
    // The half that WORKS. The two tests above pin the problem and the guard; this is the way
    // through it, and it is what a Pattern feature will be built on.
    auto source = box(40.0, 30.0, 20.0, 1);
    REQUIRE(source.ok());
    const auto top = faceName(source.value(), BoxFace::ZMax);
    REQUIRE(top.ok());

    auto moved = cad::kernel::translate(source.value().shape, 200.0, 0.0, 0.0);
    REQUIRE(moved.ok());
    cad::naming::NamingContext ctx(2, 0);
    auto copy = ctx.nameCopy(moved.value(), source.value().shape, source.value().map, {1, 0});
    REQUIRE(copy.ok());

    // Same element count -- nothing was lost in the stamping.
    CHECK(copy.value().size() == source.value().map.size());

    // And NOT the source's names: a reference to the original's top face must not resolve inside
    // the copy, or the two are the same thing again.
    CHECK_FALSE(copy.value().resolve(top.value()).has_value());

    // The original is untouched, so references taken before the copy still work.
    CHECK(source.value().map.resolve(top.value()).has_value());
}

TEST_CASE("M1: two copies of one source are distinct from each other",
          "[m1][naming][multiplicity]") {
    auto source = box(40.0, 30.0, 20.0, 1);
    REQUIRE(source.ok());

    const auto instanceMap = [&](double dx, cad::naming::NamingContext::Instance instance) {
        auto moved = cad::kernel::translate(source.value().shape, dx, 0.0, 0.0);
        REQUIRE(moved.ok());
        cad::naming::NamingContext ctx(2, 0);
        auto map = ctx.nameCopy(moved.value(), source.value().shape, source.value().map, instance);
        REQUIRE(map.ok());
        return std::pair{moved.value().shape(), std::move(map.value())};
    };

    auto [shapeA, mapA] = instanceMap(200.0, {1, 0});
    auto [shapeB, mapB] = instanceMap(400.0, {2, 0});

    // No name in one appears in the other. This is the property a pattern needs and the property
    // propagate() cannot provide.
    for (const auto& name : mapA.allNames()) {
        INFO(name.toString());
        CHECK_FALSE(mapB.resolve(name).has_value());
    }

    // Which is what makes them fusable: the collision guard now has nothing to complain about.
    auto fused = cad::kernel::booleanFuse(shapeA, shapeB);
    REQUIRE(fused.ok());
    cad::naming::NamingContext fuseCtx(3, 0);
    const cad::kernel::Shape* a = &shapeA;
    const cad::kernel::Shape* b = &shapeB;
    auto fusedMap = fuseCtx.propagate(fused.value(), {a, b}, {&mapA, &mapB});
    if (!fusedMap.ok()) INFO(fusedMap.error().detail);
    REQUIRE(fusedMap.ok());
    CHECK(fusedMap.value().collisions().empty());
}

TEST_CASE("M1: a copy's names are the same on every rebuild", "[m1][naming][multiplicity]") {
    // A name that changed between rebuilds would break every reference into the pattern the moment
    // anything upstream was edited -- the exact failure M1 exists to prevent, arriving through a
    // new door.
    const auto namesOfInstance = [](cad::naming::NamingContext::Instance instance) {
        auto source = box(40.0, 30.0, 20.0, 1);
        REQUIRE(source.ok());
        auto moved = cad::kernel::translate(source.value().shape, 200.0, 0.0, 0.0);
        REQUIRE(moved.ok());
        cad::naming::NamingContext ctx(2, 0);
        auto map = ctx.nameCopy(moved.value(), source.value().shape, source.value().map, instance);
        REQUIRE(map.ok());
        std::vector<std::string> names;
        for (const auto& name : map.value().allNames()) names.push_back(name.toString());
        std::sort(names.begin(), names.end());
        return names;
    };

    CHECK(namesOfInstance({1, 0}) == namesOfInstance({1, 0}));
    CHECK(namesOfInstance({1, 0}) != namesOfInstance({2, 0}));
}

TEST_CASE("M1: an instance is identified by its coordinate, not by a running number",
          "[m1][naming][multiplicity]") {
    // Why (i, j) rather than 0..N. A rectangular pattern numbered flat renumbers EVERY instance
    // when its row count changes -- go from 3x3 to 3x8 and the fourth hole becomes the ninth -- so
    // a fillet on it silently moves to a different hole. That is the same class of failure the
    // whole collision guard exists to prevent, arriving one level up.
    using Instance = cad::naming::NamingContext::Instance;

    // Distinct coordinates pack to distinct keys, and the two axes do not alias each other: (1,0)
    // and (0,1) are different instances, which a flat counter cannot express at all.
    CHECK(Instance{1, 0}.key() != Instance{0, 1}.key());
    CHECK(Instance{0, 0}.key() == 0u);
    CHECK(Instance{1, 2}.key() == ((1u << 16) | 2u));
    CHECK(Instance{0xFFFF, 0xFFFF}.key() == 0xFFFFFFFFu);

    // And the name follows the coordinate, so the same instance of a 3x3 and of a 3x8 pattern
    // carries the same name -- nothing about the pattern's SIZE is baked into it.
    const auto nameFor = [](Instance instance) {
        auto source = box(40.0, 30.0, 20.0, 1);
        REQUIRE(source.ok());
        auto moved = cad::kernel::translate(source.value().shape, 200.0, 0.0, 0.0);
        REQUIRE(moved.ok());
        cad::naming::NamingContext ctx(2, 0);
        auto map = ctx.nameCopy(moved.value(), source.value().shape, source.value().map, instance);
        REQUIRE(map.ok());
        std::vector<std::string> names;
        for (const auto& n : map.value().allNames()) names.push_back(n.toString());
        std::sort(names.begin(), names.end());
        return names;
    };
    CHECK(nameFor({1, 2}) == nameFor({1, 2}));
    CHECK(nameFor({1, 2}) != nameFor({2, 1}));
}

// ── split faces ────────────────────────────────────────────────────────────────────────
//
// The other half of the multiplicity problem, and the one that was already shipping. A boolean
// that cuts one face into two reports BOTH pieces as `Modified` of the same parent, so both
// claimed one name and `bind` kept the last. The earlier piece stayed in the geometry and became
// unreachable: `unnamed()` saw nothing wrong, because every face did have a name.

TEST_CASE("M1: fusing two overlapping solids names every face", "[m1][naming][splits]") {
    // Two boxes overlapping by half. Nothing exotic -- this is the most ordinary boolean there is,
    // and before split pieces were discriminated it lost eight elements silently.
    auto a = box(40.0, 30.0, 20.0, 1);
    auto b = box(40.0, 30.0, 20.0, 2);
    REQUIRE(a.ok());
    REQUIRE(b.ok());

    auto shifted = cad::kernel::translate(b.value().shape, 20.0, 0.0, 0.0);
    REQUIRE(shifted.ok());
    cad::naming::NamingContext moveCtx(2, 0);
    auto shiftedMap = moveCtx.propagate(shifted.value(), {&b.value().shape}, {&b.value().map});
    REQUIRE(shiftedMap.ok());
    const cad::kernel::Shape shiftedShape = shifted.value().shape();

    auto fused = cad::kernel::booleanFuse(a.value().shape, shiftedShape);
    REQUIRE(fused.ok());
    cad::naming::NamingContext ctx(3, 0);
    auto map = ctx.propagate(fused.value(), {&a.value().shape, &shiftedShape},
                             {&a.value().map, &shiftedMap.value()});
    if (!map.ok()) INFO(map.error().detail);
    REQUIRE(map.ok());

    CHECK(map.value().collisions().empty());
    CHECK(map.value().unnamed(fused.value().shape()).empty());

    // Every face reachable by exactly one name, and every name resolving. Counting both directions
    // is the point: the old failure had all the faces named and some of the names unreachable.
    const auto faces = fused.value().shape().subShapes(cad::kernel::ShapeType::Face);
    std::set<std::string> distinct;
    for (const auto& face : faces) {
        const auto name = map.value().nameOf(face);
        REQUIRE(name.has_value());
        distinct.insert(name->toString());
    }
    CHECK(distinct.size() == faces.size());
}

TEST_CASE("M1: a face that does not split keeps the name it always had", "[m1][naming][splits]") {
    // The compatibility half. Discriminating split siblings must not renumber anything else, or
    // every reference in every saved document moves -- which is the failure this layer exists to
    // prevent, arriving as its own fix.
    auto plain = box(40.0, 30.0, 20.0, 1);
    REQUIRE(plain.ok());
    const auto top = faceName(plain.value(), BoxFace::ZMax);
    REQUIRE(top.ok());

    // A cut that touches only one side leaves the top face whole.
    auto tool = box(10.0, 10.0, 60.0, 2);
    REQUIRE(tool.ok());
    auto moved = cad::kernel::translate(tool.value().shape, 100.0, 0.0, 0.0);
    REQUIRE(moved.ok());
    cad::naming::NamingContext moveCtx(2, 0);
    auto movedMap = moveCtx.propagate(moved.value(), {&tool.value().shape}, {&tool.value().map});
    REQUIRE(movedMap.ok());
    const cad::kernel::Shape movedShape = moved.value().shape();

    auto fused = cad::kernel::booleanFuse(plain.value().shape, movedShape);
    REQUIRE(fused.ok());
    cad::naming::NamingContext ctx(3, 0);
    auto map = ctx.propagate(fused.value(), {&plain.value().shape, &movedShape},
                             {&plain.value().map, &movedMap.value()});
    REQUIRE(map.ok());

    // The original name still resolves, unchanged and underived.
    CHECK(map.value().resolve(top.value()).has_value());
}

TEST_CASE("M1: split pieces are numbered the same way every time", "[m1][naming][splits]") {
    // A sibling index that moved between rebuilds would be worse than no index at all: every
    // reference into a split face would land on the other piece after an unrelated edit.
    const auto namesOfFuse = [] {
        auto a = box(40.0, 30.0, 20.0, 1);
        auto b = box(40.0, 30.0, 20.0, 2);
        REQUIRE(a.ok());
        REQUIRE(b.ok());
        auto shifted = cad::kernel::translate(b.value().shape, 20.0, 0.0, 0.0);
        REQUIRE(shifted.ok());
        cad::naming::NamingContext moveCtx(2, 0);
        auto shiftedMap = moveCtx.propagate(shifted.value(), {&b.value().shape}, {&b.value().map});
        REQUIRE(shiftedMap.ok());
        const cad::kernel::Shape shiftedShape = shifted.value().shape();
        auto fused = cad::kernel::booleanFuse(a.value().shape, shiftedShape);
        REQUIRE(fused.ok());
        cad::naming::NamingContext ctx(3, 0);
        auto map = ctx.propagate(fused.value(), {&a.value().shape, &shiftedShape},
                                 {&a.value().map, &shiftedMap.value()});
        REQUIRE(map.ok());
        std::vector<std::string> names;
        for (const auto& n : map.value().allNames()) names.push_back(n.toString());
        std::sort(names.begin(), names.end());
        return names;
    };
    CHECK(namesOfFuse() == namesOfFuse());
}

TEST_CASE("M1: names do not depend on the order inputs were passed", "[m1][naming][splits]") {
    // A boolean's two operands are a SET, so naming its result must not depend on which was
    // written first. It did: a merged face is bound under both names, `bind` records the first
    // binding as the shape's own name, and every edge and vertex is then derived from that -- so
    // swapping the arguments renamed geometry that had not changed.
    //
    // Invisible in one process, fatal across two: the DDC's shared tier keys on these names, so two
    // machines that assembled the same boolean differently would never hit each other's cache.
    const auto namesFor = [](bool swapped) {
        auto a = box(40.0, 30.0, 20.0, 1);
        auto b = box(40.0, 30.0, 20.0, 2);
        REQUIRE(a.ok());
        REQUIRE(b.ok());
        auto shifted = cad::kernel::translate(b.value().shape, 20.0, 0.0, 0.0);
        REQUIRE(shifted.ok());
        cad::naming::NamingContext moveCtx(2, 0);
        auto shiftedMap = moveCtx.propagate(shifted.value(), {&b.value().shape}, {&b.value().map});
        REQUIRE(shiftedMap.ok());
        const cad::kernel::Shape shiftedShape = shifted.value().shape();

        auto fused = swapped ? cad::kernel::booleanFuse(shiftedShape, a.value().shape)
                             : cad::kernel::booleanFuse(a.value().shape, shiftedShape);
        REQUIRE(fused.ok());
        cad::naming::NamingContext ctx(3, 0);
        auto map = swapped
                       ? ctx.propagate(fused.value(), {&shiftedShape, &a.value().shape},
                                       {&shiftedMap.value(), &a.value().map})
                       : ctx.propagate(fused.value(), {&a.value().shape, &shiftedShape},
                                       {&a.value().map, &shiftedMap.value()});
        REQUIRE(map.ok());
        std::vector<std::string> names;
        for (const auto& n : map.value().allNames()) names.push_back(n.toString());
        std::sort(names.begin(), names.end());
        return names;
    };
    CHECK(namesFor(false) == namesFor(true));
}
