// M1 ACCEPTANCE TEST — the gate for the whole project.
//
// The scenario that defines parametric B-rep CAD:
//
//   1. build a box
//   2. the user picks ONE edge and fillets it
//   3. an upstream parameter changes; the shape is rebuilt from scratch and every OCCT
//      index is different
//   4. the fillet must still be on the edge the user picked
//
// Naive index-based references pass step 3 by accident for small changes and break silently
// for large ones. That silent breakage is the topological naming problem.

#include "Model.h"

#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generators.hpp>
#include <catch2/generators/catch_generators_range.hpp>

#include <cstdlib>
#include <string>

using namespace cadtest;
using cad::kernel::BoxFace;
using cad::naming::contentHash;
using cad::naming::NameStep;
using cad::naming::Provenance;

namespace {

/// The name the fillet face should carry: generated by the picked edge, in feature 2.
ElementName expectedFilletFace(const ElementName& pickedEdge, std::uint32_t serial = 2) {
    NameStep s;
    s.featureSerial = serial;
    s.opTag = 0;
    s.provenance = Provenance::Generated;
    s.parents = {pickedEdge.digest()};
    return pickedEdge.derive(s);
}

}  // namespace

TEST_CASE("M1: a filleted edge survives upstream parameter changes", "[m1][naming]") {
    // Pick the edge once, at the nominal size, the way a user would.
    auto nominal = box(100.0, 60.0, 40.0);
    REQUIRE(nominal.ok());
    auto pickedR = edgeBetween(nominal.value(), BoxFace::ZMax, BoxFace::YMin);
    REQUIRE(pickedR.ok());
    const ElementName picked = pickedR.value();

    // Sweep the width. The fillet must land on the same NAMED edge every time, even though
    // OCCT's sub-shape indices are free to change arbitrarily between rebuilds.
    const double width = GENERATE(range(20.0, 220.0, 4.0));  // 50 values
    INFO("width = " << width);

    auto rebuiltBox = box(width, 60.0, 40.0);
    REQUIRE(rebuiltBox.ok());

    // The reference taken at 100mm still resolves at every other width.
    REQUIRE_FALSE(rebuiltBox.value().map.resolveAll(picked).empty());

    auto filleted = fillet(rebuiltBox.value(), picked, 5.0);
    REQUIRE(filleted.ok());
    CHECK(filleted.value().shape.validate().ok());

    // The fillet face is present and derives from the edge the user picked — not from
    // whichever edge happened to land at the same index.
    CHECK(filleted.value().map.resolve(expectedFilletFace(picked)).has_value());

    // Nothing in the result may be anonymous. An unnamed element is a future silent
    // rebinding bug; propagate() already fails on this, so reaching here means it held.
    CHECK(filleted.value().map.unnamed(filleted.value().shape).empty());
}

// ---------------------------------------------------------------------------------------
// The adversarial cases. These decide whether the scheme actually works; the sweep above is
// the easy half. Each must FAIL LOUDLY rather than rebind to the wrong element — a wrong
// answer here silently corrupts a user's model, the worst failure mode a CAD system has.

TEST_CASE("M1: a split edge keeps both children", "[m1][naming]") {
    auto base = box(100.0, 60.0, 40.0);
    REQUIRE(base.ok());
    auto pickedR = edgeBetween(base.value(), BoxFace::ZMax, BoxFace::YMin);
    REQUIRE(pickedR.ok());
    const ElementName picked = pickedR.value();

    // A notch through the middle of that edge divides it in two. Both children bound the
    // same face pair, so they share a family and differ only in discriminator.
    auto toolBox = box(20.0, 20.0, 20.0, /*serial*/ 10);
    REQUIRE(toolBox.ok());
    auto tool = translated(toolBox.value(), 40.0, -5.0, 30.0);
    REQUIRE(tool.ok());

    auto notched = cut(base.value(), tool.value());
    REQUIRE(notched.ok());

    // The exact reference no longer resolves — the original edge is gone as a single entity.
    // The family does, and it has two members.
    const auto children = notched.value().map.resolveAll(picked);
    INFO("resolved " << children.size() << " children for " << picked.toString());
    REQUIRE(children.size() == 2);

    // "Fillet this edge" therefore applies to both.
    auto filleted = fillet(notched.value(), picked, 3.0);
    REQUIRE(filleted.ok());
    CHECK(filleted.value().shape.validate().ok());
}

TEST_CASE("M1: a vanished edge fails loudly and never rebinds", "[m1][naming]") {
    auto base = box(100.0, 60.0, 40.0);
    REQUIRE(base.ok());
    auto pickedR = edgeBetween(base.value(), BoxFace::ZMax, BoxFace::YMin);
    REQUIRE(pickedR.ok());
    const ElementName picked = pickedR.value();

    // Chop the entire top-front corner away across the full width. Top and Front both
    // survive but no longer touch, so no edge bounds that pair any more.
    auto toolBox = box(140.0, 30.0, 30.0, /*serial*/ 10);
    REQUIRE(toolBox.ok());
    auto tool = translated(toolBox.value(), -20.0, -10.0, 30.0);
    REQUIRE(tool.ok());

    auto chopped = cut(base.value(), tool.value());
    REQUIRE(chopped.ok());

    // Nothing resolves — and crucially, nothing *else* resolves either.
    CHECK(chopped.value().map.resolveAll(picked).empty());

    // The dependent feature reports a legible, specific failure.
    auto filleted = fillet(chopped.value(), picked, 3.0);
    REQUIRE_FALSE(filleted.ok());
    CHECK(filleted.error().code == ErrorCode::NamingLost);
    INFO(filleted.error().message);
    CHECK(filleted.error().message.find("no longer exists") != std::string::npos);
}

TEST_CASE("M1: merged faces keep both references alive", "[m1][naming]") {
    auto a = box(100.0, 60.0, 40.0);
    REQUIRE(a.ok());
    auto bBase = box(100.0, 60.0, 40.0, /*serial*/ 20);
    REQUIRE(bBase.ok());
    auto b = translated(bBase.value(), 100.0, 0.0, 0.0);
    REQUIRE(b.ok());

    const auto aTop = faceName(a.value(), BoxFace::ZMax);
    REQUIRE(aTop.ok());

    auto merged = fuseAndUnify(a.value(), b.value());
    REQUIRE(merged.ok());
    CHECK(merged.value().shape.validate().ok());

    // The two coplanar top faces are now one face. A reference to the original top face of
    // box A must still resolve — to the merged face.
    const auto resolved = merged.value().map.resolve(aTop.value());
    REQUIRE(resolved.has_value());
    CHECK_FALSE(resolved->isNull());
    CHECK(resolved->type() == cad::kernel::ShapeType::Face);
}

TEST_CASE("M1: naming is deterministic within a process", "[m1][naming]") {
    // Non-determinism almost always enters through pointer-ordered iteration of OCCT maps.
    // Two independent builds of the same model must agree exactly.
    auto first = box(100.0, 60.0, 40.0);
    auto second = box(100.0, 60.0, 40.0);
    REQUIRE(first.ok());
    REQUIRE(second.ok());

    CHECK(nameStrings(first.value()) == nameStrings(second.value()));
    CHECK(contentHash(first.value().shape, first.value().map).hex() ==
          contentHash(second.value().shape, second.value().map).hex());

    auto e1 = edgeBetween(first.value(), BoxFace::ZMax, BoxFace::YMin);
    auto e2 = edgeBetween(second.value(), BoxFace::ZMax, BoxFace::YMin);
    REQUIRE(e1.ok());
    REQUIRE(e2.ok());
    auto f1 = fillet(first.value(), e1.value(), 5.0);
    auto f2 = fillet(second.value(), e2.value(), 5.0);
    REQUIRE(f1.ok());
    REQUIRE(f2.ok());

    CHECK(nameStrings(f1.value()) == nameStrings(f2.value()));
    CHECK(contentHash(f1.value().shape, f1.value().map).hex() ==
          contentHash(f2.value().shape, f2.value().map).hex());
}

// The cross-process half of determinism lives in m1_determinism_subprocess.cpp, because it
// needs control of main(). Without it the DDC's shared tier produces cross-machine misses
// and is worthless.

TEST_CASE("M1: names round-trip through text", "[m1][naming]") {
    auto m = box(100.0, 60.0, 40.0);
    REQUIRE(m.ok());
    for (const auto& name : m.value().map.allNames()) {
        const auto text = name.toString();
        INFO(text);
        CHECK(ElementName::parse(text) == name);
    }
}
